Fix jump pan
GuoChen-WHU/react-native-pinch-zoom-view pull request #16
Opened 2018-04-07 16:40 UTC by 3DJakob

When pinching to zoom gestureState.dx and gestureState.dy would grow like normal causing it to jump pan once one of the two fingers was released if not a perfect zoom gesture was done.

2018-04-07 16:49 UTC, albinekb approved these changes

2018-04-07 17:00 UTC, LinusU commented on index.js
> +      this.setState({lastMovePinch: false});
I would merge this with the preceding line:

```js
this.setState({ offsetX, offsetY, lastMovePinch: false });
```

2018-04-07 17:00 UTC, LinusU commented on index.js
> +      this.setState({lastMovePinch: true});
Same here:

```js
this.setState({ scale, lastMovePinch: true });
```

2018-04-08 04:06 UTC, GuoChen-WHU requested changes
Great fix! @3DJakob Thank you!  I think we can merge the setState expressions as @LinusU suggested. If you can make that update I'd love to merge this!

2018-04-09 15:54 UTC, 3DJakob commented
@GuoChen-WHU Updated 👌

2018-04-09 16:24 UTC, albinekb approved these changes

2018-04-10 02:00 UTC, GuoChen-WHU approved these changes

2018-04-10 02:02 UTC, merged